FROM node:22-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY turbo.json ./
COPY tsconfig*.json ./

COPY packages ./packages
COPY swagger ./swagger
COPY apps/validator ./apps/validator

RUN npm ci

RUN npm run generate:db

RUN cd apps/validator && npm run build

EXPOSE 3003

CMD ["npm", "run", "start:validator"]