FROM node:22-alpine
ARG DB_URL
WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./package-lock.json ./
COPY ./turbo.json ./
COPY ./packages ./packages
COPY ./apps/web/package.json ./apps/web/

RUN npm ci

COPY ./apps/web ./apps/web/

RUN npm run generate:db
RUN DB_URL=$DB_URL npx turbo build --filter=web...

EXPOSE 3000
CMD [ "npm","run","start:frontend" ]